const { contextBridge, ipcRenderer, webUtils } = require('electron');

function subscribe(channel, callback) {
  const listener = (_event, data) => callback(data);
  ipcRenderer.on(channel, listener);
  return () => ipcRenderer.removeListener(channel, listener);
}

contextBridge.exposeInMainWorld('repoAPI', {
  addRepo: (url) => ipcRenderer.invoke('repo:add', url),
  listRepos: () => ipcRenderer.invoke('repo:list'),
  getRepo: (id) => ipcRenderer.invoke('repo:get', id),
  removeRepo: (id) => ipcRenderer.invoke('repo:remove', id),
  tree: (repoId, path) => ipcRenderer.invoke('repo:tree', { repoId, path }),
  readFile: (repoId, path) => ipcRenderer.invoke('file:read', { repoId, path }),
  writeFile: (repoId, path, content) => ipcRenderer.invoke('file:write', { repoId, path, content }),
  mkdir: (repoId, path) => ipcRenderer.invoke('file:mkdir', { repoId, path }),
  rename: (repoId, from, to) => ipcRenderer.invoke('file:rename', { repoId, from, to }),
  remove: (repoId, path) => ipcRenderer.invoke('file:delete', { repoId, path }),
  duplicate: (repoId, path) => ipcRenderer.invoke('file:duplicate', { repoId, path }),
  reveal: (repoId, path) => ipcRenderer.invoke('shell:reveal', { repoId, path }),
  openExternal: (repoId, path) => ipcRenderer.invoke('shell:open', { repoId, path }),
  gitStatus: (repoId) => ipcRenderer.invoke('git:status', repoId),
  gitDiff: (repoId, path, staged) => ipcRenderer.invoke('git:diff', { repoId, path, staged }),
  gitStage: (repoId, paths) => ipcRenderer.invoke('git:stage', { repoId, paths }),
  gitUnstage: (repoId, paths) => ipcRenderer.invoke('git:unstage', { repoId, paths }),
  gitCommit: (repoId, message) => ipcRenderer.invoke('git:commit', { repoId, message }),
  gitPush: (repoId) => ipcRenderer.invoke('git:push', repoId),
  gitPull: (repoId) => ipcRenderer.invoke('git:pull', repoId),
  gitFetch: (repoId) => ipcRenderer.invoke('git:fetch', repoId),
  gitLog: (repoId) => ipcRenderer.invoke('git:log', { repoId }),
  gitShow: (repoId, commit) => ipcRenderer.invoke('git:show', { repoId, commit }),
  gitBranches: (repoId) => ipcRenderer.invoke('git:branches', repoId),
  gitCheckout: (repoId, branch) => ipcRenderer.invoke('git:checkout', { repoId, branch }),
  gitCreateBranch: (repoId, name) => ipcRenderer.invoke('git:createBranch', { repoId, name }),
  gitDiscard: (repoId, path) => ipcRenderer.invoke('git:discard', { repoId, path }),
  gitSetRemote: (repoId, url) => ipcRenderer.invoke('git:setRemote', { repoId, url }),
  githubLogin: (token) => ipcRenderer.invoke('github:login', token),
  githubLogout: () => ipcRenderer.invoke('github:logout'),
  githubMe: () => ipcRenderer.invoke('github:me'),
  githubRepos: () => ipcRenderer.invoke('github:repos'),
  githubClone: (repo) => ipcRenderer.invoke('github:clone', repo),
  githubTree: (repo, path, ref) => ipcRenderer.invoke('github:tree', { repo, path, ref }),
  githubReadFile: (repo, path, ref) => ipcRenderer.invoke('github:readFile', { repo, path, ref }),
  githubWriteFile: (repo, path, content, sha, ref) => ipcRenderer.invoke('github:writeFile', { repo, path, content, sha, ref }),
  githubDelete: (repo, path, sha, ref) => ipcRenderer.invoke('github:delete', { repo, path, sha, ref }),
  githubRename: (repo, from, to, ref) => ipcRenderer.invoke('github:rename', { repo, from, to, ref }),
  githubDuplicate: (repo, path, ref) => ipcRenderer.invoke('github:duplicate', { repo, path, ref }),
  githubUpload: (repo, destination, paths, ref) => ipcRenderer.invoke('github:upload', { repo, destination, paths, ref }),
  githubRepo: (repo) => ipcRenderer.invoke('github:repo', { repo }),
  githubBranches: (repo) => ipcRenderer.invoke('github:branches', { repo }),
  githubCommits: (repo, ref) => ipcRenderer.invoke('github:commits', { repo, ref }),
  githubReadme: (repo, ref) => ipcRenderer.invoke('github:readme', { repo, ref }),
  githubSearchTree: (repo, ref) => ipcRenderer.invoke('github:searchTree', { repo, ref }),
  githubCreateRepo: (options) => ipcRenderer.invoke('github:createRepo', options),
  githubOrgs: () => ipcRenderer.invoke('github:orgs'),
  githubGitignoreTemplates: () => ipcRenderer.invoke('github:gitignoreTemplates'),
  githubLicenses: () => ipcRenderer.invoke('github:licenses'),
  githubUpdateRepo: (repo, options) => ipcRenderer.invoke('github:updateRepo', { repo, options }),
  githubDownload: (repo, path, ref) => ipcRenderer.invoke('github:download', { repo, path, ref }),
  openWeb: (url) => ipcRenderer.invoke('shell:openWeb', url),
  getPathForFile: (file) => webUtils.getPathForFile(file),
  importPaths: (repoId, destination, paths) => ipcRenderer.invoke('import:paths', { repoId, destination, paths }),
  minimize: () => ipcRenderer.send('window:minimize'),
  maximize: () => ipcRenderer.send('window:maximize'),
  close: () => ipcRenderer.send('window:close'),
  isMaximized: () => ipcRenderer.invoke('window:isMaximized'),
  onMaximized: (callback) => subscribe('window:maximized', callback),
  onProgress: (callback) => subscribe('repo:progress', callback)
});
